extends Node

enum Style {STRAW, BASIC, COWBOY, ENGLISH, BASEBALL, BEANIE, CAP}
enum State {DEFAULT, FISHING, BUILDING, SHOP, HOUSE}
enum Tool {AXE, HOE, SWORD, WATER, FISH, SEED}
enum Machine {DELETE, SPRINKLER, FISHER, SCARECROW}
enum Seed {TOMATO, CORN, PUMPKIN, WHEAT}
enum Item {WOOD, APPLE, TOMATO, CORN, WHEAT, PUMPKIN, FISH}
enum Shop {MAIN, HAT}
enum Fish {GOLD, SILVER, GRAY}
enum KEYBOARD {CHANGE_HIGHLIGHT, CHANGE_MODE, CHANGE_TOOL, CHANGE_MACHINE, CHANGE_SEED, CHANGE_STYLE, ACTION, CHANGE_DAY, INTERACT}
